name: CI
on:
  push:
  workflow_dispatch:
    inputs:
      package-overrides:
        description: "Install specific versions of packages"
        required: false

jobs:
  test:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node:
          - "14"
          - "15"

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Install Node ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm install

      - name: Override dependency version
        if: ${{ github.event.inputs.package-overrides }}
        run: npm install ${{ github.event.inputs.package-overrides }}

      - name: Run tests
        run: npm test

